name = "remote-sql-cursor3"
# switch between proxy.ts, minimal-example.ts and high-throughput-example.ts to test the other demos
main = "minimal-example.ts"
compatibility_date = "2025-07-08"
dev.port = 3000
assets.directory = "./"

route.custom_domain = true
route.pattern = "remote-sql-cursor.wilmake.com"

limits.cpu_ms = 300000

[[durable_objects.bindings]]
name = "ExampleObject"
class_name = "ExampleObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "ExampleObject" ]