name = "remote-sql-cursor"
main = "minimal-example.ts"
compatibility_date = "2024-04-15"
dev.port = 3000
assets.directory = "./"
route.custom_domain = true
route.pattern = "remote-sql-cursor.wilmake.com"

limits.cpu_ms = 300000

[[durable_objects.bindings]]
name = "DATABASE"
class_name = "DatabaseDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "DatabaseDO" ]

